backend:
  name: github
  branch: main
  repo: owner/repo

publish_mode: editorial_workflow
media_folder: static/media
public_folder: /media

local_backend:
  url: http://localhost:8082/api/v1

collections:
  - name: posts
    label: Posts
    label_singular: 'Post'
    folder: content/posts
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    i18n: true
    fields:
      - label: Template
        name: template
        widget: hidden
        default: post
        i18n: true
      - label: Title
        name: title
        widget: string
        i18n: true
      - label: 'Cover Image'
        name: 'image'
        widget: 'image'
        required: false
        i18n: true
      - label: Publish Date
        name: date
        widget: datetime
        i18n: true
      - label: Description
        name: description
        widget: text
        i18n: true
      - label: Category
        name: category
        widget: string
        i18n: true
      - label: Body
        name: body
        widget: markdown
        i18n: true
      - label: Tags
        name: tags
        widget: list
        i18n: true
  - name: pages
    label: Pages
    label_singular: 'Page'
    folder: content/pages
    create: true
    slug: '{{slug}}'
    fields:
      - label: Template
        name: template
        widget: hidden
        default: page
      - label: Title
        name: title
        widget: string
      - label: Draft
        name: draft
        widget: boolean
        default: true
      - label: Body
        name: body
        widget: markdown
